#!/bin/sh

p() {
  printf "\033[1m\033[31m$1\033[0m\033[0m\t$2\n"
}

_pkgs() { xbps-query -l | wc -l; }
_home() { ls -A ~ | wc -l; }

printf '\n'
p os    void
p sh    zsh
p wm    sway
p term  alacritty
p font  'm+ 1m'
printf '\n'
p pkgs  $(_pkgs)
p '~/' $(_home)
printf '\n'
