#!/bin/sh

reload_alacritty() {
  cp $XDG_CACHE_HOME/wal/alacritty.yml $XDG_CONFIG_HOME/alacritty/alacritty.yml
}

reload_qutebrowser() {
  qutebrowser ':config-source'
}

reload_oguri() {
  cp $XDG_CACHE_HOME/wal/oguri $XDG_CONFIG_HOME/oguri/config
  pkill oguri; oguri &
}

reload_mako() {
  cp $XDG_CACHE_HOME/wal/mako $XDG_CONFIG_HOME/mako/config
  pkill mako; mako &
}

reload_swaylock() {
  cp $XDG_CACHE_HOME/wal/swaylock $XDG_CONFIG_HOME/swaylock/config;
}

reload_alacritty
reload_oguri
reload_mako
reload_swaylock
reload_qutebrowser
