#!/bin/sh

install_config() {
  install "$XDG_CACHE_HOME/wal/$1" "$2"
}

check_running() {
  pgrep -x "$1" > /dev/null 2>&1
}

# oguri
# inst oguri "$XDG_CONFIG_HOME/oguri/config"
# pkill oguri; oguri &

# mako
install_config mako "$XDG_CONFIG_HOME/mako/config"
pkill mako; mako &

# swaylock
install_config swaylock "$XDG_CONFIG_HOME/swaylock/config"

# zathura
install_config zathurarc "$XDG_CONFIG_HOME/zathura/zathurarc"

# qutebrowser
check_running qutebrowser && qutebrowser ":config-source" &
