#!/bin/sh

for i in $@; do
  case $i in
    -h |--help)
      echo "\
usage: wofile (dir) [options]

options:
  --help        -h  shows this message and exit
  --restricted  -r  don't allow user to leave the initial dir"
      exit
    ;;

    -r|--restricted)
      r=1
    ;;

    -*)
      echo "unknow argument $i"; exit
    ;;
    
    *)
      if [ -z $dir ]; then
        dir=$i
      else
        echo "too many arguments"; exit
      fi
    ;;
  esac
  shift
done

[ -z $dir ] && dir=~
[ -d $dir ] || exit

choice=$dir

while [ -d $choice ]; do
  cd $choice;

  if [ "$dir" -ef "$PWD" ] && [ $r ]; then
    choice=$( ls | wofi -d )
  else
    choice=$( (echo ..; ls) | wofi -d )
  fi

  [ -z $choice ] && exit
done

echo "$PWD/$choice"
