#!/bin/sh

for i in $@; do
  [ $i = "-r" ] || [ $i = "--restricted" ] && r=1
done

[ -z $dir ] && dir=~
[ -d $dir ] || exit

choice=$dir

while [ -d $choice ]; do
  cd $choice;

  if [ "$dir" -ef "$PWD" ] && [ $r ]; then
    choice=$( ls | wofi -d )
  else
    choice=$( (echo ..; ls) | wofi -d )
  fi

  [ -z $choice ] && exit
done

echo "$PWD/$choice"
